services:
  - type: web
    name: easy-market
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:socket_app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FLW_SECRET_KEY
        sync: false
      - key: FLW_PUBLIC_KEY
        sync: false
      - key: FLW_ENCRYPTION_KEY
        sync: false
      - key: ADMIN_SECRET
        sync: false
      - key: ENV
        value: production
